#!/bin/bash

# 1) rename this file - change ifyna-example to the name of the application user
# 2) rename ifyna-example in this file to the application user
# 3) put or link this file into /etc/init.d
# 4) enable this script for default runlevels, running:
#    $ sudo update-rc.d tomcat-ifyna-example defaults
#
### BEGIN INIT INFO
# Provides: $syslog
# Required-Start: $local_fs
# Required-Stop: $local_fs
# Default-Start:  2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: tomcat example 
# Description: tomcat example 
### END INIT INFO

case "$1" in
  *)
    su -c "~/server/bin/tomcat.sh $1" - ifyna-example
    ;;
esac

exit $?